# Generated by Django 4.2.10 on 2025-07-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='download_url',
            field=models.URLField(blank=True, verbose_name='Ссылка для скачивания'),
        ),
    ]
